services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    container_name: nimble-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nimble

  redis:
    image: redis:latest
    container_name: nimble-redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
