packages:
  - apps/*
  - packages/**/

onlyBuiltDependencies:
  - '@database/generated'
  - '@prisma/client'
  - '@prisma/engines'
  - cpu-features
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - ssh2
